---
fontsize: 12pt
linestretch: 2
output:
  pdf_document: default
  html_document: default
---

We will consider outcomes as the change in each of the variables in table 3 over one year, as well as change in cortical thickness over one year. Using linear regression, we will model these continuous outcomes predicted by all inflammatory markers (also continuous) at baseline (1a.) and difference over a year of markers (1b.). We will explore variable distributions, outliers, and missingness to see whether data transformation (e.g. log-transforming right-skewed variables) or filtering is necessary. Missing values and outliers will be flagged and potentially removed. We will assess covariates (age, sex, CV risk, immunological health history conditions, APOE genotype, baseline outcome values) and determine whether they are confounders (causally affecting the predictors and outcomes), precision variables (causally affecting the outcome), or mediators (variables through which the predictor impacts the outcome), using both domain knowledge and regression result assessment. We will check whether covariates are highly correlated with each other. If two precision variables are strongly correlated, only the more predictive one will be kept in the model. We will test the overall effect of the predictors on the outcomes in the presence of age, sex, and precision variables, using a partial F-test on the inclusion of markers (or change in markers) in the model at alpha = .05 and test the sensitivity of the result to the inclusion of confounders and mediators. If predictors are strongly correlated (correlation of IL-6 and MCP-1 in preliminary data is .93), we will assess individual predictor level effects in models stratified by predictor, again adjusting for aforementioned covariates and testing effect estimates at an alpha level of .... ***multiple comparisons***. Unless model assessment shows poor fit, we will assume linear relationships between the outcomes and predictors.

For Aim 2, we will include amyloid deposition and its interaction with predictors to models which were significantly predictive in Aim 1, again adjusting for aforementioned covariates and testing result sensitivity to confounding, using analogous testing methods to Aim 1. If none of the models showed an effect in Aim 1, we will consider including interaction to all of the predefined models. 