---
title: "P2 Interim Analysis Plan"
author: "Jacob Kebe"
output: pdf_document
documentclass: article
geometry: margin=1in
fontsize: 12pt
linestretch: 2
header-includes:
  - \usepackage{setspace}
  - \doublespacing
  - \usepackage{multirow}
  - \usepackage{amsmath}
  - \usepackage{amssymb}
  - \usepackage{dcolumn}
  - \usepackage{fvextra}
  - \usepackage{bm}
---

**Aim 1**

We will test the hypothesis that higher presence of inflammatory markers (IL-6, TNF-alpha,MCP-1,Eotaxin-1) at baseline contributes to a decline in cortical thickness and 5 cognitive measures over 1 year, with measures at baseline and 1 year. The cognitive measures are \
- California Verbal Learning Test-II (CVLT) 20' delay, total correct and \
- CVLT recognition, D-prime, \
- Benson Figure 15' Delay, Total Correct, \
- Mnemonic Similarity Task (MST) Proportion Correct, and \
- Story Recall 1-week delay, total correct. \
We will also assess whether an increase in inflammatory markers over 1 year is associated decline in outcomes.

**Aim 2**

We will consider another predictor, amyloid deposition, and test whether its inclusion and interaction with the predictors in modelling outcomes contributes to decline over one year.

**Models**

For each outcome, using linear regression, we will model the difference over a year predicted by all inflammatory markers at baseline (Aim 1 Hyp 1a.) and difference over a year of markers (1b.), and if significant relationships shown in models including all predictors and covariates (overall F test, individual level t-tests), we will include amyloid deposition at baseline and its interaction with respective predictors in significantly predictive models (overall F test) from Aim 1. We will consider dichotomizing amyloid deposition (C.6.d) for ease of interpretability. We will also consider stratifying linear models by predictors, and removing certain covariates, in the presence of strong associations between any of the variables (multicollinearity).

**Covariates**

We have information on demographic and health history measures, and will adjust for age, sex, CV risk, immunological health history conditions, and APOE genotype, assessing which conditions to include in the models by analyzing the correlation between the conditions and the other conditions, as well as predictors of interest to avoid multicollinearity.

**Power Analysis**

I will use power calculations for correlation, since we will eventually perform regression with continuous outcomes and predictors, assessing a reasonable correlation under the alternative hypothesis. We can test how much power will be provided given the sample size provided by the investigator, as well as how large a sample would be needed to achieve a power of .7,.8, and .9 to compare. It may be a good idea to adjust alpha level. We may also need to consider power calculations for overall model tests.